### ISSUE TITLE
Duplicate DOM (possible cach problem)

### ISSUE THREAD

**Issue by arkirchner** [chrismccord/sync#188] opened 2015-05-13 15:23 UTC
Good Evening,

I am suck with an error related to sync (and Faye). I have my two partials 'role' and 'new_role_edit'. First I only used the 'role' partial and everything worked fine. Then I added the the 'new_role_edit' and called it after the 'role' partial like this:
```
  <div class="col-md-7 col-md-offset-1" id="roles">
    <% @roles.each do |role| %>
      <%= sync partial: 'role', resource: role %>
      <div id="<%= "role-form-#{role.id}" %>" style="display:none;"></div>
    <% end %>
    <%= sync_new partial: 'role', resource: Role.new %>
    <%= sync_new partial: 'new_role_edit', resource: Role.new %>
  </div>
```
Now when I add a new line I get two new roles (only one is created through). When I look in the console I can see both partials being loaded two times. I deleted the second sync_new but still both partials are loaded two times. Then I used 'rake tmp:clear' and deleted the  'new_role_edit' partial. Now when I want to create a new role I get the following error message. I am not calling the 'new_role_edit' in my code but sill it says it is missing. When I restore the partial I end up having the role Duplicate (only one in the database). How can I reset the partial and how can I use two partials?

Thank you very much for your help! I am a beginner with rails ... I hope my mistake is not to silly. 

Completed 500 Internal Server Error in 103ms (ActiveRecord: 0.3ms)

ActionView::MissingTemplate (Missing partial sync/roles/_new_role_edit with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :jbuilder]}. Searched in:
  * "/media/daten/Dokumente/PBKK/kanri-soft/app/views"
  * "/home/akirchner/.gem/ruby/gems/ckeditor-4.1.1/app/views"
  * "/home/akirchner/.gem/ruby/gems/devise-3.4.1/app/views"
):

Sincerely
A. Kirchner

**Comment by ajb** [comment] 2015-07-05 19:58
Hi @arkirchner, sorry for the delay in response. I don't think there's any errors in the code you've posted, so if you're still having trouble with this, could you post your controller code as well? One possible workaround might be to create a new partial, let's call it "new_role_with_edit", that includes the content form both the "role" as well as the "new_role_edit" partials. That way you would only be calling `sync_new` one time. Does that make sense? 

I'm going to close this issue since I don't think there's a bug in Sync, but if you reply I'll do my best to help you troubleshoot the issue.

-- Adam

**Closed by ajb** 2015-07-05 19:58 UTC

**Comment by arkirchner** [comment] 2015-07-07 10:26
Hello Adam

Thank you for your help. I did what you asked me and now I am calling only <%= sync_new partial: 'new_role_edit', resource: Role.new %>.

Unnaturally now I get the new role partial three times. I think I do something wrong with the cache. I deleted a sync partial and every time I run update in the controller it asks me for the partial. This partial is not called in my code anywhere. I think that is the issue here. I deleted rails cache many times and it is not helping. Can you give me a hint how I let Faye/Sync know to not call old partials?

Here is my controller code:
```ruby
   def create
    if @role  = Role.create(role_params)
      sync_new @role
      respond_with(@role)
    else
      respond_with(@role)
    end
  end

  def update
    if @role.update_attributes(role_params)
      # flash[:success] = "Post was updated! #{make_undo_link}"
      sync_update @role
      respond_with(@role)
    else
      respond_with(@role)
    end
  end

  def destroy
    @role.destroy
    sync_destroy @role
  end
```

Sincerely
Armin

**Comment by ajb** [comment] 2015-07-07 13:25
Hey Armin,

That code looks perfect. Are you calling `sync :all` inside of your model? If so, that would be the cause of the duplicate partials.

If you're able to publish your entire application, I can clone it down and see if I can recreate the problem. You're also welcome to create an isolated test case, but it might be a little more difficult to do than just publishing your entire app.

**Comment by arkirchner** [comment] 2015-07-08 08:45
Hello Adam,

thank you for your answer. I am not calling sync:all in my app. Thank you so much for looking into it.

In my eyes this is the most basic implementation of sync but it dose the double new products if you add one.

https://github.com/arkirchner/sync_test

The sync partials are called in:
```
app/views/products/_products.html.erb
```
I renamed it to 'product_test' and deleted the 'product' partial but it still wants to have 'product'. So I had to put an empty partial to get rid of the error. This is the cache problem I am talking about.
```
<%= sync_new partial: 'product_test', resource: Product.new %>
<%= sync partial: 'product_test', resource: product %>
```
If you have any questions please let me know. Sorry for the trouble. I am still new in Rails (my first app). I hope you understand my app. 

Sincerely
Armin

**Comment by ajb** [comment] 2015-07-08 12:37
Hi Armin,

Your text editor must be generating duplicate files:

![img](http://take.ms/JZk83)

This is most likely the cause of your issue.

**Comment by arkirchner** [comment] 2015-07-08 15:21
Hello Adam,

this is the issue. Thank you so much for helping me! I feel so silly. :-|

I must start using vim and stop using gedit.

Sorry for wasting your time with this. Now everything works just fine.

Sincerely
Armin Kirchner
