### ISSUE TITLE
Support PubNub

### ISSUE THREAD

**Issue by nadeemja** [chrismccord/sync#90] opened 2014-01-25 12:51 UTC
Hi,

Do you have any intentions for supporting PubNub?
It seems very competitive. 

Here are some links for you:

http://www.pubnub.com/

What are the pros and cons of using Pusher vs PubNub?
http://www.quora.com/Push-Notifications/What-are-the-pros-and-cons-of-using-Pusher-vs-PubNub-or-any-other-push-APIs

PubNub ruby gem
https://github.com/pubnub/ruby

How complicated would it be for you to support PubNub?

Regards,

Nadeem

**Comment by BrokenChair** [comment] 2015-04-26 18:21
PubNub support would be much appreciated. Like Nadeem, I'm new to the pull requests and such, but I'd be willing to help with what I can.

**Comment by ajb** [comment] 2016-02-06 14:50
Closing as a duplicate of #8.

**Closed by ajb** 2016-02-06 14:50 UTC
Labels: enhancement
